[project]
name = "bowserapi-tests"
version = "0.1.0"
description = "BowserAPI Tests - A Flask API testing project"
requires-python = ">=3.9"
dependencies = [
    "flask==3.1.1",
    "flasgger",
    "flask-sqlalchemy",
    "flask-marshmallow",
    "marshmallow-sqlalchemy",
]
